# Generated by Django 4.1.6 on 2023-04-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_alter_furniture_price_alter_furniture_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
