# Generated by Django 4.1.6 on 2023-04-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0005_alter_furniture_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shippingPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='taxPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shippingPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
