export const CART_ADD_FURNITURE = "CART_ADD_FURNITURE"; 
export const CART_REMOVE_FURNITURE = "CART_REMOVE_FURNITURE"; 

export const CART_SAVE_SHIPPING_DETAILS = "CART_SAVE_SHIPPING_DETAILS"

export const FURNITURE_INCREASE_QTY = "FURNITURE_INCREASE_QTY";
export const FURNITURE_DECREASE_QTY = "FURNITURE_DECREASE_QTY";

export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";
export const CART_CLEAR_SHIPPING_DETAILS = "CART_CLEAR_SHIPPING_DETAILS";
export const CART_CLEAR_PAYMENT_METHOD = "CART_CLEAR_PAYMENT_METHOD";


